# Generated by Django 3.2.9 on 2025-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BesoinArrosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Besoin en arrosage',
                'verbose_name_plural': 'Besoins en arrosage',
            },
        ),
        migrations.CreateModel(
            name='BesoinSoleil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Besoin en soleil',
                'verbose_name_plural': 'Besoins en soleil',
            },
        ),
        migrations.CreateModel(
            name='CategoriePlante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie de plante',
                'verbose_name_plural': 'Catégories de plantes',
            },
        ),
        migrations.CreateModel(
            name='FamillePlante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Famille de plante',
                'verbose_name_plural': 'Familles de plantes',
            },
        ),
        migrations.CreateModel(
            name='TypeSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de sol',
                'verbose_name_plural': 'Types de sol',
            },
        ),
    ]
