# Generated by Django 3.2.9 on 2025-08-31 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantes_configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudePointFaible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AptitudePointFort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategorieAptitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelePlante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun', models.CharField(max_length=200)),
                ('nom_latin', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plantes/')),
                ('debut_semis', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True)),
                ('fin_semis', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True)),
                ('debut_recolte', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True)),
                ('fin_recolte', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True)),
                ('espacement_plants', models.FloatField(blank=True, help_text='Distance entre deux plants (cm)', null=True)),
                ('espacement_lignes', models.FloatField(blank=True, help_text='Distance entre deux lignes (cm)', null=True)),
                ('besoin_arrosage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantes_configuration.besoinarrosage')),
                ('besoin_soleil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantes_configuration.besoinsoleil')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantes_configuration.categorieplante')),
                ('famille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantes_configuration.familleplante')),
                ('points_faibles', models.ManyToManyField(to='plantes.AptitudePointFaible')),
                ('points_forts', models.ManyToManyField(to='plantes.AptitudePointFort')),
                ('type_sol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantes_configuration.typesol')),
            ],
            options={
                'verbose_name': 'plante',
                'verbose_name_plural': 'plantes',
                'ordering': ['nom_commun'],
            },
        ),
        migrations.AddField(
            model_name='aptitudepointfort',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantes.categorieaptitude'),
        ),
        migrations.AddField(
            model_name='aptitudepointfaible',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantes.categorieaptitude'),
        ),
    ]
