# Generated by Django 3.2.9 on 2025-09-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantes_configuration', '0001_initial'),
        ('plantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeleplante',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantes_configuration.categorieplante'),
        ),
        migrations.AlterField(
            model_name='modeleplante',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantes_configuration.familleplante'),
        ),
        migrations.AlterField(
            model_name='modeleplante',
            name='points_faibles',
            field=models.ManyToManyField(blank=True, to='plantes.AptitudePointFaible'),
        ),
        migrations.AlterField(
            model_name='modeleplante',
            name='points_forts',
            field=models.ManyToManyField(blank=True, to='plantes.AptitudePointFort'),
        ),
    ]
