# Generated by Django 3.2.9 on 2025-09-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantes', '0002_auto_20250904_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationPlante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMPAGNONNAGE', 'Compagnonnage'), ('INCOMPATIBILITE', 'Incompatibilite')], max_length=200)),
                ('plante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plante1', to='plantes.modeleplante', verbose_name='Plante 1')),
                ('plante2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plante2', to='plantes.modeleplante', verbose_name='Plante 2')),
            ],
            options={
                'verbose_name': 'Association de plante',
                'verbose_name_plural': 'Associations de plantes',
                'ordering': ['plante1', 'plante2', 'type'],
                'unique_together': {('plante1', 'plante2')},
            },
        ),
    ]
