# Generated by Django 3.2.9 on 2025-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantes', '0003_associationplante'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationplante',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
