# Generated by Django 3.2.9 on 2025-09-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantes', '0004_associationplante_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationplante',
            options={'ordering': ['type'], 'verbose_name': 'Association de plante', 'verbose_name_plural': 'Associations de plantes'},
        ),
        migrations.AddField(
            model_name='associationplante',
            name='plantes',
            field=models.ManyToManyField(help_text='Plantes associées dans cette association', related_name='associations', to='plantes.ModelePlante'),
        ),
        migrations.AlterUniqueTogether(
            name='associationplante',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='associationplante',
            name='plante1',
        ),
        migrations.RemoveField(
            model_name='associationplante',
            name='plante2',
        ),
    ]
